// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABU5Kn75xti-1-rfKkrA7YL6n6h4z9Na0',
    appId: '1:568991676619:web:489417715df4cac827034e',
    messagingSenderId: '568991676619',
    projectId: 'avd-flutter-lab',
    authDomain: 'avd-flutter-lab.firebaseapp.com',
    storageBucket: 'avd-flutter-lab.firebasestorage.app',
    measurementId: 'G-1E9102PNP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrA1PP9Kx3jRUhKy8EnwK6ZQxt7O_P67w',
    appId: '1:568991676619:android:4f64a035d5a80b3427034e',
    messagingSenderId: '568991676619',
    projectId: 'avd-flutter-lab',
    storageBucket: 'avd-flutter-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZP7HUOlRKb5yJRBbu_G6ckNYQJ5oiBo0',
    appId: '1:568991676619:ios:8dbf35cd8313607a27034e',
    messagingSenderId: '568991676619',
    projectId: 'avd-flutter-lab',
    storageBucket: 'avd-flutter-lab.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanceLab',
  );
}
